# Generated by Django 3.1 on 2020-08-23 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0008_auto_20200823_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay',
            name='question',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
